# .github/workflows/auto-merge.yml
name: Enable Auto-Merge (all PRs to main)
on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

