# .github/workflows/auto-merge.yml
name: Enable Auto-Merge (PRs to main)

on:
  pull_request_target:
    branches: [ main ]
    types: [ opened, reopened, synchronize, ready_for_review ]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    # чтобы красный крестик от этого job не мешал PR
    continue-on-error: true
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
